version: "3.8"

services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=UTC
    ports:
      - "5432:5432"
    networks:
      - demoapp-network

  application:
    container_name: demo-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - postgresql
    networks:
      - demoapp-network

networks:
  demoapp-network:
    driver: bridge

volumes:
  postgresql-data: